config/routes.rb
Rails.application.routes.draw do
  get 'braintree/new'
  get 'welcome/index'
  root "listings#index"
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

resources :listings do
  resources :reservations
end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"
  get "/profile" => "users#show", as: "profile"
  post 'braintree/checkout'
  get "/search_page" => "listings#search", as: "search_page"
  post "/advance_search" => "listings#advance_search", as: "advance_search"
  post "/index_search" => "listings#index_search", as: "index_search"
  get "/index_search" => "listings#index"
  post '/search', to: 'listings#auto_search'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end
        

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"],
      token: auth_hash["credentials"]["token"]
    )
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
	belongs_to :user
	has_many :reservations

	scope :city, -> (city) {where(city: city)}
	scope :state, -> (state) {where(state: state)}
	scope :p_type, -> (p_type) {where(property_type: p_type)}
	scope :b_number, -> (b_num) { where(bed_number: b_um) }
	scope :r_number, -> (r_num) { where(room_number: r_um) }

	include PgSearch
  	pg_search_scope :search_by_city, :against => [:city, :state]

	mount_uploaders :images, ImageUploader

	def self.search(search_params)
		if search_params
			Listing.where("city ilike ? AND state ilike ? AND property_type = ? AND bed_number = ? AND room_number = ? ", "%#{search_params[:city]}%", "%#{search_params[:state]}%", search_params[:property_type], search_params[:bed_number], search_params[:room_number])
		else
			Listing.all
		end
	end

	def self.search_city(query)
		where("city ILIKE :city", city: "%#{query}%").map do |record|
      		record.city 
  		end
	end

end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :user
	belongs_to :listing
end

app/models/user.rb
class User < ApplicationRecord

 include Clearance::User

 has_many :authentications, dependent: :destroy
 has_many :listings
 has_many :reservations

 enum role: [:customer, :moderator, :superadmin]

 mount_uploader :image, ImageUploader

 def self.create_with_auth_and_hash(authentication, auth_hash)
   user = self.create!(
     name: auth_hash["info"]["name"],
     email: auth_hash["info"]["email"],
     password: SecureRandom.hex(10)
   )
   user.authentications << authentication
   return user
 end

 # grab google to access google for user data
 def google_token
   x = self.authentications.find_by(provider: 'google_oauth2')
   return x.token unless x.nil?
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller

  def index
  end

  # def new
  # end

  # def create
  # 	@user = User.new(params[:user])
  # 	if @user.save 
  # 		redirect_to user_path(@user.id)
  # 	else
  # 		render :new
  # 	end
  # end
end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def new
  	@client_token = Braintree::ClientToken.generate
  end

  def checkout
  nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

  result = Braintree::Transaction.sale(
   :amount => "10.00", #this is currently hardcoded
   :payment_method_nonce => nonce_from_the_client,
   :options => {
      :submit_for_settlement => true
    }
   )

  if result.success?
    redirect_to :root, :flash => { :success => "Transaction successful!" }
  else
    redirect_to :root, :flash => { :error => "Transaction failed. Please try again." }
  end
end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

	def index 
      @view_listing = Listing.all.paginate(:page => params[:page], :per_page => 15)
  	end

  	def new
  		@listing = Listing.new

  		if current_user.customer?
			flash[:notice] = "Sorry. You are not allowed to perform this action."
        redirect_to root_url, notice: "Sorry. You do not have the permissino to verify a property."
      	end
  	end

  	def create
  		listing = Listing.new(listing_params)
  		listing.user_id = current_user.id
  		
  		if listing.save 
  			redirect_to root_url
  		else
  			p 'failed to add listing'
  			redirect_to new_listing_path
  		end
  	end

  	def show
  		@listing = Listing.find(params[:id])
  	end

    def search 
      @search_listing = Listing.new
    end


    def advance_search
      @view_listing = Listing.search(search_params).paginate(:page => params[:page], :per_page => 15)
      render "index"
    end

    def index_search
      @view_listing = Listing.search_by_city(index_params[:city]).paginate(:page => params[:page], :per_page => 15)
      render "index"
      if @view_listing = "" 
        return root_url, notice: "It's empty"
      end
    end

    def auto_search
      @cities = Listing.search_city(params[:city])
      respond_to do |format|
        format.json { render json: @cities }
        format.js
      end
    end

  	private

  	def listing_params
  		params.require(:listing).permit(:country, :state, :city, :postcode, :address, :property_type, :room_number, :bed_number, :guest_number, :tags, :price, :description, {images: []})
  	end

    def search_params
      params.require(:listing).permit(:state, :city, :property_type,:bed_number, :room_number)
    end

    def index_params
    params.require(:listing).permit(:city) 
    end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	def new 
		@listing = Listing.find(params[:listing_id])
		@reservation = Reservation.new
	end

	def create
		reservation = Reservation.new(reservations_params)

		reservation.user_id = current_user.id
		reservation.listing_id = params[:listing_id]
		
		if reservation.save
			ReservationJob.perform_later(current_user)
			# ReservationMailer.reservation_email(current_user).deliver_now
			redirect_to root_url
		else
			p 'failed to add listing'
			redirect_to root_url
		end
	end

	private

  	def reservations_params
  		params.require(:reservation).permit(:check_in_date, :check_out_date, :book_guest_number, :memo)
  	end

end


# params = { reservation: {year: 2019, month: "August"}}

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController

	def create
		user = User.new(user_from_params)

		if user.save
			redirect_to sign_in_path
		else
			p 'failed to sign up'
			redirect_to sign_up_path
		end
	end

	def show 
		user_id = current_user.id
		@reservation = Reservation.where(user_id: user_id)
	end

	private

	def user_from_params
		# Add in original code from Clearance GitHub (user controller)
		# Add in additional fields like first name, last name
		params.require(:user).permit(:email, :password, :username, :first_name, :last_name, :gender, :phone_number, :country)

	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
	    case level
	        when :success then "alert alert-success"
	        when :error then "alert alert-error"
	    end
	end
end

app/helpers/braintree_helper.rb
module BraintreeHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/application/index.html.erb
<h1>Welcome to Airbnb</h1>
<img src="https://cdn.iconscout.com/icon/free/png-256/airbnb-1-282216.png" height="150" width="150">

<% if signed_in? %>
  Signed in as: <%= current_user.email %>
  <%= button_to 'Sign out', sign_out_path, method: :delete %>
<% else %>
  <button><%= link_to 'Sign in', sign_in_path %></button>
<% end %>



<p>or</p>

<button><%= link_to "Sign in with Google", "/auth/google_oauth2" %></button>

app/views/braintree/new.html.erb
<h1>Braintree#new</h1>
<div class="demo-frame">

  <%= form_for :checkout_form, url: braintree_checkout_path, html: { id: "cardForm"} do |form| %>

    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>

    <%= form.hidden_field "payment_method_nonce" %>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: true, class: "btn btn-primary", id: "submit-payment-btn" %>
    </div>
  <% end %>
</div>



<!-- Load the Client component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

<!-- Load the Hosted Fields component. -->
<script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

<script>
      var form = document.querySelector('#cardForm');
      var submit = document.querySelector('#submit-payment-btn');
      var authorization = '<%= @client_token %>';

      braintree.client.create({
        authorization: authorization
      }, function (clientErr, clientInstance) {
        if (clientErr) {
          console.error(clientErr);
          return;
        }

        // This example shows Hosted Fields, but you can also use this
        // client instance to create additional components here, such as
        // PayPal or Data Collector.

        braintree.hostedFields.create({
          client: clientInstance,
          styles: {
            'input': {
              'font-size': '14px'
            },
            'input.invalid': {
              'color': 'red'
            },
            'input.valid': {
              'color': 'green'
            }
          },
          fields: {
            number: {
              selector: '#card-number',
              placeholder: '4111 1111 1111 1111'
            },
            cvv: {
              selector: '#cvv',
              placeholder: '123'
            },
            expirationDate: {
              selector: '#expiration-date',
              placeholder: '10/2019'
            }
          }
        }, function (hostedFieldsErr, hostedFieldsInstance) {
          if (hostedFieldsErr) {
            console.error(hostedFieldsErr);
            return;
          }

          submit.removeAttribute('disabled');

          form.addEventListener('submit', function (event) {
            event.preventDefault();

            hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
              if (tokenizeErr) {
                console.error(tokenizeErr);
                return;
              }

              // If this was a real integration, this is where you would
              // send the nonce to your server.
              document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
              form.submit();
            });
          }, false);
        });
      });
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

    <link rel="icon" href="/favicomatic/favicon.ico" type="image/png" sizes="16x16" />

  </head>

  <body>

    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/listings/index.html.erb
<header>
	<%= link_to root_path do %>
			<%= image_tag "https://img.icons8.com/color/1600/airbnb.png", class: "airbnb-logo" %>
	<% end %>
</header>
<div>
	<br class="shadow-line">
	<button class="nav-buttons">
		<%= button_to 'Sign out', sign_out_path, method: :delete, id: "sign-out-button" %>
	</button>
	<button class="nav-buttons"><%= link_to 'Profile', profile_path, method: :get %></button>
	<% if current_user.superadmin? %>
		<button class ="nav-buttons"><%= link_to 'Add listing', new_listing_path  %></button>
	<% end %>
	Hi <%= current_user.first_name %> !
	<button class="nav-buttons"><%= link_to 'Advance search', search_page_path, method: :get %></button>
</div>

<hr>

<%= form_for "listing", url: index_search_path, html: { id: "auto_search" } do |i| %>
	<%= i.label "Search by City:", class: 'search-bar' %>
	<%= i.text_field :city, :autocomplete => :off, id: "search-field" , list: "list" %>
	<datalist id="list"></datalist>
	<%= i.submit "Search", class: 'search-button' %>
<% end %>

<% @view_listing.each do |listing| %>
<div class="listing">	
	<h5 class="listing-block">
		<%= listing.property_type %>
	</h5> at
	<h4 class="listing-block">
		<%= listing.city %>
	</h4>

	<br>

	<h5 class="listing-block">RM<%= listing.price %></h5> <p class="listing-block">per person</p>

	<div class="list-buttons">
		<%= button_to 'View details', listing_path(listing), method: :get, class: "list-button" %>
		<%= button_to "Make reservation", new_listing_reservation_path(listing.id), method: :get, class: "list-button" %>
	</div>
	
	<hr>
</div>
<% end %> 
</br> 


<div class="flickr_pagination" >
	<%= will_paginate @view_listing %>
</div>

app/views/listings/new.html.erb
<h2 class="add-listing-header">Any listing to add?</h2>

<div class="add-listing-form">
  <%= form_with model: @listing, local: true do |l| %>
    <%= l.label :"Country:" %>
    <%= l.text_field :country ,class: "add-listing-bar" %>
    <br>
    <%= l.label :"State:" %>
    <%= l.text_field :state ,class: "add-listing-bar"%>
    <br>
    <%= l.label :"City:" %>
    <%= l.text_field :city ,class: "add-listing-bar"%>
    <br>
    <%= l.label :"Postcode:" %>
    <%= l.text_field :postcode,class: "add-listing-bar" %>
    <br>
    <%= l.label :"Address:" %>
    <%= l.text_field :address,class: "add-listing-bar" %>
    <br>
    <%= l.label :'Property type:' %>
    <%= l.text_field :property_type,class: "add-listing-bar" %>
    <br>
    <%= l.label :'Room number:' %>
    <%= l.text_field :room_number,class: "add-listing-bar" %>
    <br>
    <%= l.label :'Bed number:' %>
    <%= l.text_field :bed_number,class: "add-listing-bar" %>
    <br>
    <%= l.label :'Guest number:' %>
    <%= l.text_field :guest_number,class: "add-listing-bar" %>
    <br>
    <%= l.label :"Tags:" %>
    <%= l.text_field :tags,class: "add-listing-bar" %>
    <br>
    <%= l.label :"Price:" %>
    <%= l.text_field :price,class: "add-listing-bar" %>
    <br>
    <%= l.label :"Description:" %>
    <%= l.text_field :description ,class: "add-listing-bar"%>
    <br>

    <%= l.file_field :images, multiple: true %>

    <br>
    <%= l.submit class: "search-button" %>
  <% end %>

  <%= button_to 'Main Page', root_path, method: :get, class:'main-button list-button' %>
</div>

app/views/listings/search.html.erb
<h1>Advance search</h1>

<div class="add-listing-form">
	<%= form_for @search_listing, url: advance_search_path do |f| %>
		<%= f.label "State: " %>
		<%= f.text_field :state %>
		<br>
		<%= f.label "City: " %>
		<%= f.text_field :city %>
		<br>
		<%= f.label "Property type" %>
		<%= f.select :property_type, [['House', 'House'],['Entire floor', 'Entire floor'], ['Townhouse', 'Townhouse'], ['Condominium', 'Condominium'], ['Villa', 'Villa'], ['Castle', 'Castle'], ['Treehouse', 'Treehouse']] %>
		<br>
		<%= f.label "Bed number" %>
		<%= f.select :bed_number, [['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5'], ['6', '6']] %>
		<br>
			<%= f.label "Room number" %>
		<%= f.select :room_number, [['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5'], ['6', '6']] %>
		<br>
		<%= f.submit 'Search' ,class: "search-button" %>
	<% end %>
</div>

<%= button_to 'Main Page', root_path, method: :get, class:'main-button list-button' %>

<%=  @view_search_listing %>

app/views/listings/show.html.erb
<h2 class="view-head">
	<%= @listing.property_type %>
</h2> 
<h5 class="view-head">at</h5>
<h3 class="view-head">
	<%= @listing.city %>
</h3>
<br>

<!-- Price -->
<div class="view-head">
	<img src="https://image.flaticon.com/icons/svg/134/134547.svg" class="view-img">
	<h5>RM<%= @listing.price %></h5>
</div>

<br>

<!-- Location -->
<div class="view-head">
	<img src="https://image.flaticon.com/icons/svg/149/149441.svg" class="view-img">
	<h5><%= @listing.address %>, <%= @listing.postcode %>, <%= @listing.city %>, <%= @listing.state %></h5>
</div>

<br>

<!-- Owner -->
<div class="view-head">
	<img src="https://image.flaticon.com/icons/svg/149/149452.svg" class="view-img">
	<h5><%= @listing.user.username %> <%= @listing.user.last_name %></h5>
</div>

<br>

<!-- Number of Room & Number of Bed -->
<div class="view-head">
	<img src="https://image.flaticon.com/icons/svg/248/248212.svg" class="view-img">
	<h5 class="room_and_bed"><%= @listing.room_number %></h5>
	<img src="https://image.flaticon.com/icons/svg/259/259963.svg" class="view-img">
	<h5 class="room_and_bed"><%= @listing.bed_number %></h5>
	<img src="https://image.flaticon.com/icons/svg/149/149447.svg" class="view-img">
	<h5><%= @listing.guest_number %></h5>
</div>

<br>

<!-- Description -->
<div class="view-head">
	<img src="https://image.flaticon.com/icons/svg/134/134816.svg" class="view-img">
	<h5><%= @listing.description %></h5>
</div>

<br>

<% @listing.images.each do |image| %>
	<%= image_tag(image.url , class: "view-stay-img") %> 
<% end %>

<%= button_to 'Main Page', root_path, method: :get, class:'main-button list-button' %>

app/views/reservations/new.html.erb
<h1>Make your reservation here</h1>

<%= form_with model: [@listing, @reservation] do |r| %>
	<%= r.label :'Check in date' %>
	<%= r.text_field :check_in_date %>
	<br>
	<%= r.label :'Check out date' %>
	<%= r.text_field :check_out_date %>
	<br>
	<%= r.label :'Guest number'%>
	<%= r.text_field :book_guest_number %>
	<br>
	<%= r.label :'Memo to the host'%>
	<%= r.text_field :memo %>
	<br>
	<%= r.submit "Instant Book" %>
<% end %>

<%= button_to 'Main Page', root_path, method: :get %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :Email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :Password %>
  <%= form.password_field :password %>
</div>

<div class="text-field">
  <%= form.label :Username %>
  <%= form.text_field :username %>
</div>

<div class="text-field">
  <%= form.label :'First name' %>
  <%= form.text_field :first_name %>
</div>

<div class="text-field">
  <%= form.label :'Last name' %>
  <%= form.text_field :last_name %>
</div>

<div class="text-field">
  <%= form.label :Gender %>
  <%= form.text_field :gender %>
</div>

<div class="text-field">
  <%= form.label :'Phone number' %>
  <%= form.text_field :phone %>
</div>

<div class="text-field">
  <%= form.label :Country %>
  <%= form.text_field :country %>
</div>

<!-- Add in additional fields for new table colums (first name, last name, etc.) -->

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div>
        <%= form.submit %>
    </div>

    <div class="other-links">
      <button class="main-page-button"><%= link_to t(".sign_in"), sign_in_path %></button>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class='profile-head'>
	<h1>Hi <%= current_user.first_name %> !</h1>
	<%= button_to 'Main Page', root_path, method: :get, class: "main-page-button" %>
</div>

<div class="profile-details">
	<h4>Your reservation:</h4>
	<br>
	<% @reservation.each do |show_reservation| %>
		<img src="https://image.flaticon.com/icons/svg/149/149064.svg", class="show-img">
		Address: <strong><%= show_reservation.listing.address %>, <%= show_reservation.listing.postcode %>, <%= show_reservation.listing.city %>, <%= show_reservation.listing.state %></strong>
		<br>
		Check In: <strong><%= show_reservation.check_in_date %></strong>
		<br>
		Check Out: <strong><%= show_reservation.check_out_date %></strong>
		<br>
		Memo: <strong><%= show_reservation.memo %></strong>
		<hr>
	<% end %>
</div>



<%= button_to "Make Payment", braintree_new_path, method: :get, class: "main-page-button" %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>